import json
import os
from urllib.parse import urlparse

# --- Configuration ---
LINKS_FILE = "links.json"
OUTPUT_HTML_FILE = "index.html"
BASE_URL = "https://gunavault.github.io/onet-platform/"
# Update the BASE_URL to your actual GitHub Pages domain (e.g., https://johndoe.github.io/my-short-links/)
# Note: For this client-side hack to work, the URL must look like:
# BASE_URL?c=shortcode (e.g., https://base.url/?c=about)

# --- Utility Functions ---

def load_links():
    """Loads the link map from the JSON file."""
    if not os.path.exists(LINKS_FILE):
        return {}
    with open(LINKS_FILE, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"Error reading {LINKS_FILE}. Starting with an empty map.")
            return {}

def save_links(links):
    """Saves the link map to the JSON file."""
    with open(LINKS_FILE, 'w') as f:
        json.dump(links, f, indent=4)
    print(f"\n[SUCCESS] Links saved to {LINKS_FILE}.")

def is_valid_url(url):
    """Checks if the provided string is a valid URL."""
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except:
        return False

def generate_html(links):
    """Generates the single index.html file with embedded JavaScript lookup table."""
    
    # Dump the Python dictionary as a JavaScript object string
    js_links_map = json.dumps(links, indent=4)

    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL Redirect Service</title>
    <!-- Use Tailwind CSS for a clean, responsive layout -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {{ font-family: 'Inter', sans-serif; }}
    </style>
</head>
<body class="bg-gray-50 flex items-center justify-center min-h-screen p-4">

    <div id="status-card" class="bg-white p-8 rounded-xl shadow-2xl w-full max-w-md text-center">
        <div id="loader" class="mb-4">
            <svg class="animate-spin h-8 w-8 text-indigo-600 mx-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
        </div>
        <h1 id="status-title" class="text-xl font-bold text-gray-800 mb-2">Looking up short link...</h1>
        <p id="status-message" class="text-gray-500">You should be redirected momentarily.</p>
        <a id="redirect-link" href="#" class="hidden mt-4 inline-block text-indigo-600 hover:text-indigo-800 font-medium">Click here if nothing happens.</a>
    </div>

    <script>
        // The embedded JSON map generated by the Python script
        const linkMap = {js_links_map};
        
        // Base URL for the public display
        const BASE_URL = "{BASE_URL}";

        /**
         * Utility function to get query parameters from the URL
         * Expects a URL structure like: https://your.domain/?c=shortcode
         */
        function getQueryParam(param) {{
            const urlParams = new URLSearchParams(window.location.search);
            return urlParams.get(param);
        }}

        function initRedirect() {{
            const shortCode = getQueryParam('c');
            const statusTitle = document.getElementById('status-title');
            const statusMessage = document.getElementById('status-message');
            const redirectLink = document.getElementById('redirect-link');
            const loader = document.getElementById('loader');

            if (shortCode) {{
                const targetUrl = linkMap[shortCode];
                
                if (targetUrl) {{
                    // Found the link, proceed to redirect
                    loader.innerHTML = '<span class="text-3xl">✅</span>';
                    statusTitle.textContent = "Success! Redirecting...";
                    statusMessage.textContent = "Redirecting to " + targetUrl.substring(0, 50) + '...';
                    redirectLink.href = targetUrl;
                    redirectLink.classList.remove('hidden');

                    // Perform the actual client-side redirect
                    window.location.replace(targetUrl);
                }} else {{
                    // Link not found
                    loader.innerHTML = '<span class="text-3xl">❌</span>';
                    statusTitle.textContent = "Error: Link Not Found";
                    statusMessage.textContent = "The short code '" + shortCode + "' does not exist in our system.";
                }}
            }} else {{
                // No short code provided (user landed on the root page)
                loader.innerHTML = '<span class="text-3xl">🔗</span>';
                statusTitle.textContent = "Static URL Shortener Base";
                statusMessage.innerHTML = "Append `?c=yourcode` to the URL to test a short link.<br>Current links are managed via the local Python tool.";
            }}
        }}

        // Run the redirection logic when the page loads
        initRedirect();
    </script>
</body>
</html>
"""
    with open(OUTPUT_HTML_FILE, 'w') as f:
        f.write(html_content)
    print(f"[SUCCESS] Final static website ({OUTPUT_HTML_FILE}) generated.")


def add_link(links):
    """Prompts user to add a new link."""
    print("\n--- ADD NEW LINK ---")
    while True:
        short_code = input("Enter a SHORT CODE (e.g., 'about', 'cv'): ").strip()
        if not short_code:
            print("Short code cannot be empty.")
            continue
        if short_code in links:
            print(f"Error: Short code '{short_code}' already exists and points to: {links[short_code]}")
            choice = input("Overwrite? (y/N): ").strip().lower()
            if choice != 'y':
                return

        long_url = input("Enter the FULL destination URL (e.g., https://www.google.com): ").strip()
        if not is_valid_url(long_url):
            print("Error: Invalid URL format. Please include http:// or https://")
            continue
        
        links[short_code] = long_url
        save_links(links)
        generate_html(links)
        print(f"\n[INFO] Test Link: {BASE_URL}?c={short_code}")
        break

def view_links(links):
    """Displays all current links."""
    print("\n--- CURRENT LINKS ---")
    if not links:
        print("No links currently defined.")
        return
    
    # Calculate column widths
    max_code_len = max(len(code) for code in links) if links else 0
    
    print("-" * (max_code_len + 5 + 75))
    print(f"| {'SHORT CODE'.ljust(max_code_len)} | {'DESTINATION URL'.ljust(70)} |")
    print("-" * (max_code_len + 5 + 75))
    
    for code, url in links.items():
        print(f"| {code.ljust(max_code_len)} | {url[:70].ljust(70)} |") # Truncate URL for display
    print("-" * (max_code_len + 5 + 75))
    print(f"\nBASE URL: {BASE_URL}")


def main():
    """Main application loop."""
    print("Static Link Shortener Manager (Python Tool)")
    print("------------------------------------------")
    
    # IMPORTANT: Check if BASE_URL is configured
    if BASE_URL.startswith("https://YOUR_GITHUB_USERNAME"):
        print("\n[CRITICAL WARNING] Please update the BASE_URL in link_manager.py to your actual GitHub Pages domain before proceeding.")
        return

    links = load_links()

    while True:
        print("\n--- MENU ---")
        print("1. View Current Links")
        print("2. Add/Update Link")
        print("3. Regenerate HTML file (Force)")
        print("4. Exit")
        
        choice = input("Enter choice (1-4): ").strip()
        
        if choice == '1':
            view_links(links)
        elif choice == '2':
            add_link(links)
        elif choice == '3':
            generate_html(links)
        elif choice == '4':
            print("Exiting. Remember to commit and push 'index.html' to GitHub!")
            break
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")

if __name__ == "__main__":
    main()
